[[apps]]
name = "scoop"
cmd = "scoop"
args = ["cleanup", "*"]
interactive = false

[[apps]]
name = "npm"
cmd = "npm"
args = ["cache", "clean", "--force"]
interactive = false

[[apps]]
name = "yarn"
cmd = "yarn"
args = ["cache", "clean"]
interactive = false

[[apps]]
name = "cleanmgr"
cmd = "cleanmgr"
args = ["/d", "/c", "/verylowdisk"]
interactive = true

[[apps]]
name = "brew"
cmd = "brew"
args = ["cleanup"]
interactive = false

[[apps]]
name = "brew autoremove"
cmd = "brew"
args = ["autoremove"]
interactive = false
    
[[apps]]
name = "apt clean"
cmd = "apt"
args = "clean"
interactive = false

[[apps]]
name = "apt autoremove"
cmd = "apt"
args = ["autoremove"]
interactive = false
