[[apps]]
name = "scoop"
cmd = "scoop"
args = ["cleanup", "*"]
interactive = false

[[apps]]
name = "npm"
cmd = "npm"
args = ["cache", "clean", "--force"]
interactive = false

[[apps]]
name = "yarn"
cmd = "yarn"
args = ["cache", "clean"]
interactive = false

[[apps]]
name = "cleanmgr"
cmd = "cleanmgr"
args = ["/d", "/c", "/verylowdisk"]
interactive = true

[[apps]]
name = "brew"
cmd = "brew"
args = ["cleanup"]
interactive = false
    
[[apps]]
name = "apt"
cmd = "apt"
args = "clean"
interactive = false

[[apps]]
name = "pacman"
cmd = "pacman"
args = ["-Scc"]
interactive = false

[[apps]]
name = "yum"
cmd = "yum"
args = ["clean", "all"]
interactive = false

[[apps]]
name = "apk"
cmd = "apk"
args = ["cache", "clean"]
interactive = false
