name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ci_on_os:
    name: CI
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose

  ci_on_container:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [debian, fedora, archlinux, alpine]
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
